title: Nachhaltig in Frohnleiten
description: dies und das
author:
  name: Nachhaltig in Frohnleiten
  email: info@nachhaltig-in-frohnleiten.at
show_excerpts: false # set to true to show excerpts on the homepage

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

# set up remote_theme
remote_theme: "mmistakes/so-simple-theme@3.2.0"

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"
  
  skin: solarized
  
logo: "assets/Logo1.jpeg"
